// Code generated by protoc-gen-go. DO NOT EDIT.
// source: RegiAndLog.proto

package RegiAndLog

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 包含用户名称的请求消息。
type RegisteredUserRequest struct {
	Num                  string   `protobuf:"bytes,1,opt,name=Num,proto3" json:"Num,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisteredUserRequest) Reset()         { *m = RegisteredUserRequest{} }
func (m *RegisteredUserRequest) String() string { return proto.CompactTextString(m) }
func (*RegisteredUserRequest) ProtoMessage()    {}
func (*RegisteredUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_RegiAndLog_594b9def5c33dacd, []int{0}
}
func (m *RegisteredUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisteredUserRequest.Unmarshal(m, b)
}
func (m *RegisteredUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisteredUserRequest.Marshal(b, m, deterministic)
}
func (dst *RegisteredUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisteredUserRequest.Merge(dst, src)
}
func (m *RegisteredUserRequest) XXX_Size() int {
	return xxx_messageInfo_RegisteredUserRequest.Size(m)
}
func (m *RegisteredUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisteredUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisteredUserRequest proto.InternalMessageInfo

func (m *RegisteredUserRequest) GetNum() string {
	if m != nil {
		return m.Num
	}
	return ""
}

func (m *RegisteredUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

// 包含问候语的响应消息
type RegisteredUserReply struct {
	Num                  string   `protobuf:"bytes,1,opt,name=Num,proto3" json:"Num,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	Result               string   `protobuf:"bytes,3,opt,name=Result,proto3" json:"Result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisteredUserReply) Reset()         { *m = RegisteredUserReply{} }
func (m *RegisteredUserReply) String() string { return proto.CompactTextString(m) }
func (*RegisteredUserReply) ProtoMessage()    {}
func (*RegisteredUserReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_RegiAndLog_594b9def5c33dacd, []int{1}
}
func (m *RegisteredUserReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisteredUserReply.Unmarshal(m, b)
}
func (m *RegisteredUserReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisteredUserReply.Marshal(b, m, deterministic)
}
func (dst *RegisteredUserReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisteredUserReply.Merge(dst, src)
}
func (m *RegisteredUserReply) XXX_Size() int {
	return xxx_messageInfo_RegisteredUserReply.Size(m)
}
func (m *RegisteredUserReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisteredUserReply.DiscardUnknown(m)
}

var xxx_messageInfo_RegisteredUserReply proto.InternalMessageInfo

func (m *RegisteredUserReply) GetNum() string {
	if m != nil {
		return m.Num
	}
	return ""
}

func (m *RegisteredUserReply) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegisteredUserReply) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

// 包含用户名称的请求消息。
type LoginUserRequest struct {
	Num                  string   `protobuf:"bytes,1,opt,name=Num,proto3" json:"Num,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginUserRequest) Reset()         { *m = LoginUserRequest{} }
func (m *LoginUserRequest) String() string { return proto.CompactTextString(m) }
func (*LoginUserRequest) ProtoMessage()    {}
func (*LoginUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_RegiAndLog_594b9def5c33dacd, []int{2}
}
func (m *LoginUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginUserRequest.Unmarshal(m, b)
}
func (m *LoginUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginUserRequest.Marshal(b, m, deterministic)
}
func (dst *LoginUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginUserRequest.Merge(dst, src)
}
func (m *LoginUserRequest) XXX_Size() int {
	return xxx_messageInfo_LoginUserRequest.Size(m)
}
func (m *LoginUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginUserRequest proto.InternalMessageInfo

func (m *LoginUserRequest) GetNum() string {
	if m != nil {
		return m.Num
	}
	return ""
}

func (m *LoginUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

// 包含问候语的响应消息
type LoginUserReply struct {
	Num                  string   `protobuf:"bytes,1,opt,name=Num,proto3" json:"Num,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	Result               string   `protobuf:"bytes,3,opt,name=Result,proto3" json:"Result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginUserReply) Reset()         { *m = LoginUserReply{} }
func (m *LoginUserReply) String() string { return proto.CompactTextString(m) }
func (*LoginUserReply) ProtoMessage()    {}
func (*LoginUserReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_RegiAndLog_594b9def5c33dacd, []int{3}
}
func (m *LoginUserReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginUserReply.Unmarshal(m, b)
}
func (m *LoginUserReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginUserReply.Marshal(b, m, deterministic)
}
func (dst *LoginUserReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginUserReply.Merge(dst, src)
}
func (m *LoginUserReply) XXX_Size() int {
	return xxx_messageInfo_LoginUserReply.Size(m)
}
func (m *LoginUserReply) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginUserReply.DiscardUnknown(m)
}

var xxx_messageInfo_LoginUserReply proto.InternalMessageInfo

func (m *LoginUserReply) GetNum() string {
	if m != nil {
		return m.Num
	}
	return ""
}

func (m *LoginUserReply) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *LoginUserReply) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*RegisteredUserRequest)(nil), "RegiAndLog.RegisteredUserRequest")
	proto.RegisterType((*RegisteredUserReply)(nil), "RegiAndLog.RegisteredUserReply")
	proto.RegisterType((*LoginUserRequest)(nil), "RegiAndLog.LoginUserRequest")
	proto.RegisterType((*LoginUserReply)(nil), "RegiAndLog.LoginUserReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreeterClient interface {
	RegisteredUser(ctx context.Context, in *RegisteredUserRequest, opts ...grpc.CallOption) (*RegisteredUserReply, error)
	LoginUser(ctx context.Context, in *LoginUserRequest, opts ...grpc.CallOption) (*LoginUserReply, error)
}

type greeterClient struct {
	cc *grpc.ClientConn
}

func NewGreeterClient(cc *grpc.ClientConn) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) RegisteredUser(ctx context.Context, in *RegisteredUserRequest, opts ...grpc.CallOption) (*RegisteredUserReply, error) {
	out := new(RegisteredUserReply)
	err := c.cc.Invoke(ctx, "/RegiAndLog.Greeter/RegisteredUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) LoginUser(ctx context.Context, in *LoginUserRequest, opts ...grpc.CallOption) (*LoginUserReply, error) {
	out := new(LoginUserReply)
	err := c.cc.Invoke(ctx, "/RegiAndLog.Greeter/LoginUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreeterServer is the server API for Greeter service.
type GreeterServer interface {
	RegisteredUser(context.Context, *RegisteredUserRequest) (*RegisteredUserReply, error)
	LoginUser(context.Context, *LoginUserRequest) (*LoginUserReply, error)
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_RegisteredUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisteredUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).RegisteredUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RegiAndLog.Greeter/RegisteredUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).RegisteredUser(ctx, req.(*RegisteredUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_LoginUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).LoginUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RegiAndLog.Greeter/LoginUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).LoginUser(ctx, req.(*LoginUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "RegiAndLog.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisteredUser",
			Handler:    _Greeter_RegisteredUser_Handler,
		},
		{
			MethodName: "LoginUser",
			Handler:    _Greeter_LoginUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "RegiAndLog.proto",
}

func init() { proto.RegisterFile("RegiAndLog.proto", fileDescriptor_RegiAndLog_594b9def5c33dacd) }

var fileDescriptor_RegiAndLog_594b9def5c33dacd = []byte{
	// 230 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x08, 0x4a, 0x4d, 0xcf,
	0x74, 0xcc, 0x4b, 0xf1, 0xc9, 0x4f, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x42, 0x88,
	0x28, 0xb9, 0x72, 0x89, 0x82, 0x78, 0xc5, 0x25, 0xa9, 0x45, 0xa9, 0x29, 0xa1, 0xc5, 0xa9, 0x45,
	0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42, 0x02, 0x5c, 0xcc, 0x7e, 0xa5, 0xb9, 0x12, 0x8c,
	0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x20, 0xa6, 0x90, 0x14, 0x17, 0x47, 0x40, 0x62, 0x71, 0x71, 0x79,
	0x7e, 0x51, 0x8a, 0x04, 0x13, 0x58, 0x18, 0xce, 0x57, 0x8a, 0xe6, 0x12, 0x46, 0x37, 0xa6, 0x20,
	0xa7, 0x92, 0x34, 0x43, 0x84, 0xc4, 0xb8, 0xd8, 0x82, 0x52, 0x8b, 0x4b, 0x73, 0x4a, 0x24, 0x98,
	0xc1, 0x32, 0x50, 0x9e, 0x92, 0x03, 0x97, 0x80, 0x4f, 0x7e, 0x7a, 0x66, 0x1e, 0xf9, 0xce, 0x0b,
	0xe3, 0xe2, 0x43, 0x32, 0x81, 0x6a, 0x2e, 0x33, 0x5a, 0xc5, 0xc8, 0xc5, 0xee, 0x5e, 0x94, 0x9a,
	0x5a, 0x92, 0x5a, 0x24, 0x14, 0xc6, 0xc5, 0x87, 0x1a, 0x04, 0x42, 0x8a, 0x7a, 0x48, 0x41, 0x8f,
	0x35, 0x94, 0xa5, 0xe4, 0xf1, 0x29, 0x29, 0xc8, 0xa9, 0x54, 0x62, 0x10, 0x72, 0xe7, 0xe2, 0x84,
	0xbb, 0x5d, 0x48, 0x06, 0x59, 0x3d, 0x7a, 0xa0, 0x48, 0x49, 0xe1, 0x90, 0x05, 0x1b, 0xe4, 0x24,
	0xc4, 0x25, 0x90, 0x99, 0xaf, 0x97, 0x5e, 0x54, 0x90, 0xac, 0x97, 0x5a, 0x91, 0x98, 0x5b, 0x90,
	0x93, 0x5a, 0x9c, 0xc4, 0x06, 0x4e, 0x11, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd9, 0xe4,
	0x0f, 0x82, 0x25, 0x02, 0x00, 0x00,
}
