// Code generated by protoc-gen-go. DO NOT EDIT.
// source: delete.proto

package delete

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DeleteAnswerRequest struct {
	Question             string   `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	Answerer             string   `protobuf:"bytes,2,opt,name=answerer,proto3" json:"answerer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAnswerRequest) Reset()         { *m = DeleteAnswerRequest{} }
func (m *DeleteAnswerRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteAnswerRequest) ProtoMessage()    {}
func (*DeleteAnswerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_delete_036580e6a4f8b1b1, []int{0}
}
func (m *DeleteAnswerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAnswerRequest.Unmarshal(m, b)
}
func (m *DeleteAnswerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAnswerRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteAnswerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAnswerRequest.Merge(dst, src)
}
func (m *DeleteAnswerRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteAnswerRequest.Size(m)
}
func (m *DeleteAnswerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAnswerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAnswerRequest proto.InternalMessageInfo

func (m *DeleteAnswerRequest) GetQuestion() string {
	if m != nil {
		return m.Question
	}
	return ""
}

func (m *DeleteAnswerRequest) GetAnswerer() string {
	if m != nil {
		return m.Answerer
	}
	return ""
}

type DeleteAnswerReply struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAnswerReply) Reset()         { *m = DeleteAnswerReply{} }
func (m *DeleteAnswerReply) String() string { return proto.CompactTextString(m) }
func (*DeleteAnswerReply) ProtoMessage()    {}
func (*DeleteAnswerReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_delete_036580e6a4f8b1b1, []int{1}
}
func (m *DeleteAnswerReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAnswerReply.Unmarshal(m, b)
}
func (m *DeleteAnswerReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAnswerReply.Marshal(b, m, deterministic)
}
func (dst *DeleteAnswerReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAnswerReply.Merge(dst, src)
}
func (m *DeleteAnswerReply) XXX_Size() int {
	return xxx_messageInfo_DeleteAnswerReply.Size(m)
}
func (m *DeleteAnswerReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAnswerReply.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAnswerReply proto.InternalMessageInfo

func (m *DeleteAnswerReply) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func (m *DeleteAnswerReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type DeleteQuestionRequest struct {
	Question             string   `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	Questioner           string   `protobuf:"bytes,2,opt,name=questioner,proto3" json:"questioner,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteQuestionRequest) Reset()         { *m = DeleteQuestionRequest{} }
func (m *DeleteQuestionRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteQuestionRequest) ProtoMessage()    {}
func (*DeleteQuestionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_delete_036580e6a4f8b1b1, []int{2}
}
func (m *DeleteQuestionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteQuestionRequest.Unmarshal(m, b)
}
func (m *DeleteQuestionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteQuestionRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteQuestionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteQuestionRequest.Merge(dst, src)
}
func (m *DeleteQuestionRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteQuestionRequest.Size(m)
}
func (m *DeleteQuestionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteQuestionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteQuestionRequest proto.InternalMessageInfo

func (m *DeleteQuestionRequest) GetQuestion() string {
	if m != nil {
		return m.Question
	}
	return ""
}

func (m *DeleteQuestionRequest) GetQuestioner() string {
	if m != nil {
		return m.Questioner
	}
	return ""
}

type DeleteQuestionReply struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteQuestionReply) Reset()         { *m = DeleteQuestionReply{} }
func (m *DeleteQuestionReply) String() string { return proto.CompactTextString(m) }
func (*DeleteQuestionReply) ProtoMessage()    {}
func (*DeleteQuestionReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_delete_036580e6a4f8b1b1, []int{3}
}
func (m *DeleteQuestionReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteQuestionReply.Unmarshal(m, b)
}
func (m *DeleteQuestionReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteQuestionReply.Marshal(b, m, deterministic)
}
func (dst *DeleteQuestionReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteQuestionReply.Merge(dst, src)
}
func (m *DeleteQuestionReply) XXX_Size() int {
	return xxx_messageInfo_DeleteQuestionReply.Size(m)
}
func (m *DeleteQuestionReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteQuestionReply.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteQuestionReply proto.InternalMessageInfo

func (m *DeleteQuestionReply) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func (m *DeleteQuestionReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*DeleteAnswerRequest)(nil), "delete.DeleteAnswerRequest")
	proto.RegisterType((*DeleteAnswerReply)(nil), "delete.DeleteAnswerReply")
	proto.RegisterType((*DeleteQuestionRequest)(nil), "delete.DeleteQuestionRequest")
	proto.RegisterType((*DeleteQuestionReply)(nil), "delete.DeleteQuestionReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreeterClient interface {
	DeleteAnswer(ctx context.Context, in *DeleteAnswerRequest, opts ...grpc.CallOption) (*DeleteAnswerReply, error)
	DeleteQuestion(ctx context.Context, in *DeleteQuestionRequest, opts ...grpc.CallOption) (*DeleteQuestionReply, error)
}

type greeterClient struct {
	cc *grpc.ClientConn
}

func NewGreeterClient(cc *grpc.ClientConn) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) DeleteAnswer(ctx context.Context, in *DeleteAnswerRequest, opts ...grpc.CallOption) (*DeleteAnswerReply, error) {
	out := new(DeleteAnswerReply)
	err := c.cc.Invoke(ctx, "/delete.Greeter/DeleteAnswer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) DeleteQuestion(ctx context.Context, in *DeleteQuestionRequest, opts ...grpc.CallOption) (*DeleteQuestionReply, error) {
	out := new(DeleteQuestionReply)
	err := c.cc.Invoke(ctx, "/delete.Greeter/DeleteQuestion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreeterServer is the server API for Greeter service.
type GreeterServer interface {
	DeleteAnswer(context.Context, *DeleteAnswerRequest) (*DeleteAnswerReply, error)
	DeleteQuestion(context.Context, *DeleteQuestionRequest) (*DeleteQuestionReply, error)
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_DeleteAnswer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAnswerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).DeleteAnswer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/delete.Greeter/DeleteAnswer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).DeleteAnswer(ctx, req.(*DeleteAnswerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_DeleteQuestion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteQuestionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).DeleteQuestion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/delete.Greeter/DeleteQuestion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).DeleteQuestion(ctx, req.(*DeleteQuestionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "delete.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeleteAnswer",
			Handler:    _Greeter_DeleteAnswer_Handler,
		},
		{
			MethodName: "DeleteQuestion",
			Handler:    _Greeter_DeleteQuestion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "delete.proto",
}

func init() { proto.RegisterFile("delete.proto", fileDescriptor_delete_036580e6a4f8b1b1) }

var fileDescriptor_delete_036580e6a4f8b1b1 = []byte{
	// 242 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0x49, 0xcd, 0x49,
	0x2d, 0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xf0, 0x94, 0x7c, 0xb9, 0x84,
	0x5d, 0xc0, 0x2c, 0xc7, 0xbc, 0xe2, 0xf2, 0xd4, 0xa2, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12,
	0x21, 0x29, 0x2e, 0x0e, 0x30, 0x23, 0x33, 0x3f, 0x4f, 0x82, 0x51, 0x81, 0x51, 0x83, 0x33, 0x08,
	0xce, 0x07, 0xc9, 0x25, 0x82, 0x15, 0xa7, 0x16, 0x49, 0x30, 0x41, 0xe4, 0x60, 0x7c, 0x25, 0x57,
	0x2e, 0x41, 0x54, 0xe3, 0x0a, 0x72, 0x2a, 0x85, 0xc4, 0xb8, 0xd8, 0x8a, 0x52, 0x8b, 0x4b, 0x73,
	0x4a, 0xc0, 0x46, 0x71, 0x04, 0x41, 0x79, 0x42, 0x12, 0x5c, 0xec, 0xb9, 0xa9, 0xc5, 0xc5, 0x89,
	0xe9, 0xa9, 0x50, 0x73, 0x60, 0x5c, 0xa5, 0x60, 0x2e, 0x51, 0x88, 0x31, 0x81, 0x50, 0x4b, 0x89,
	0x71, 0x97, 0x1c, 0x17, 0x17, 0x8c, 0x0d, 0x77, 0x19, 0x92, 0x88, 0x92, 0x3b, 0xcc, 0xab, 0x08,
	0x43, 0xc9, 0x72, 0x9d, 0xd1, 0x62, 0x46, 0x2e, 0x76, 0xf7, 0xa2, 0xd4, 0xd4, 0x92, 0xd4, 0x22,
	0x21, 0x0f, 0x2e, 0x1e, 0x64, 0x0f, 0x0b, 0x49, 0xeb, 0x41, 0x83, 0x19, 0x4b, 0xa8, 0x4a, 0x49,
	0x62, 0x97, 0x2c, 0xc8, 0xa9, 0x54, 0x62, 0x10, 0xf2, 0xe3, 0xe2, 0x43, 0x75, 0x9e, 0x90, 0x2c,
	0xaa, 0x72, 0xb4, 0xb0, 0x90, 0x92, 0xc6, 0x25, 0x0d, 0x36, 0xcf, 0x49, 0x88, 0x4b, 0x20, 0x33,
	0x5f, 0x2f, 0xbd, 0xa8, 0x20, 0x59, 0x2f, 0xb5, 0x22, 0x31, 0xb7, 0x20, 0x27, 0xb5, 0x38, 0x89,
	0x0d, 0x1c, 0xf9, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x68, 0xb0, 0x45, 0x49, 0x0c, 0x02,
	0x00, 0x00,
}
