// Code generated by protoc-gen-go. DO NOT EDIT.
// source: DeleteAnswerAndQuestion.proto

package DeleteAnswerAndQuestion

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 包含用户名称的请求消息。
type DeleteAnswerRequest struct {
	Question             string   `protobuf:"bytes,1,opt,name=Question,proto3" json:"Question,omitempty"`
	Answerer             string   `protobuf:"bytes,2,opt,name=Answerer,proto3" json:"Answerer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAnswerRequest) Reset()         { *m = DeleteAnswerRequest{} }
func (m *DeleteAnswerRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteAnswerRequest) ProtoMessage()    {}
func (*DeleteAnswerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_DeleteAnswerAndQuestion_aacfde6a6691a807, []int{0}
}
func (m *DeleteAnswerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAnswerRequest.Unmarshal(m, b)
}
func (m *DeleteAnswerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAnswerRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteAnswerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAnswerRequest.Merge(dst, src)
}
func (m *DeleteAnswerRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteAnswerRequest.Size(m)
}
func (m *DeleteAnswerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAnswerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAnswerRequest proto.InternalMessageInfo

func (m *DeleteAnswerRequest) GetQuestion() string {
	if m != nil {
		return m.Question
	}
	return ""
}

func (m *DeleteAnswerRequest) GetAnswerer() string {
	if m != nil {
		return m.Answerer
	}
	return ""
}

// 包含问候语的响应消息
type DeleteAnswerReply struct {
	Result               string   `protobuf:"bytes,1,opt,name=Result,proto3" json:"Result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAnswerReply) Reset()         { *m = DeleteAnswerReply{} }
func (m *DeleteAnswerReply) String() string { return proto.CompactTextString(m) }
func (*DeleteAnswerReply) ProtoMessage()    {}
func (*DeleteAnswerReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_DeleteAnswerAndQuestion_aacfde6a6691a807, []int{1}
}
func (m *DeleteAnswerReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAnswerReply.Unmarshal(m, b)
}
func (m *DeleteAnswerReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAnswerReply.Marshal(b, m, deterministic)
}
func (dst *DeleteAnswerReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAnswerReply.Merge(dst, src)
}
func (m *DeleteAnswerReply) XXX_Size() int {
	return xxx_messageInfo_DeleteAnswerReply.Size(m)
}
func (m *DeleteAnswerReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAnswerReply.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAnswerReply proto.InternalMessageInfo

func (m *DeleteAnswerReply) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type DeleteQuestionRequest struct {
	Question             string   `protobuf:"bytes,1,opt,name=Question,proto3" json:"Question,omitempty"`
	Questioner           string   `protobuf:"bytes,2,opt,name=Questioner,proto3" json:"Questioner,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteQuestionRequest) Reset()         { *m = DeleteQuestionRequest{} }
func (m *DeleteQuestionRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteQuestionRequest) ProtoMessage()    {}
func (*DeleteQuestionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_DeleteAnswerAndQuestion_aacfde6a6691a807, []int{2}
}
func (m *DeleteQuestionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteQuestionRequest.Unmarshal(m, b)
}
func (m *DeleteQuestionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteQuestionRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteQuestionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteQuestionRequest.Merge(dst, src)
}
func (m *DeleteQuestionRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteQuestionRequest.Size(m)
}
func (m *DeleteQuestionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteQuestionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteQuestionRequest proto.InternalMessageInfo

func (m *DeleteQuestionRequest) GetQuestion() string {
	if m != nil {
		return m.Question
	}
	return ""
}

func (m *DeleteQuestionRequest) GetQuestioner() string {
	if m != nil {
		return m.Questioner
	}
	return ""
}

// 包含问候语的响应消息
type DeleteQuestionReply struct {
	Result               string   `protobuf:"bytes,1,opt,name=Result,proto3" json:"Result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteQuestionReply) Reset()         { *m = DeleteQuestionReply{} }
func (m *DeleteQuestionReply) String() string { return proto.CompactTextString(m) }
func (*DeleteQuestionReply) ProtoMessage()    {}
func (*DeleteQuestionReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_DeleteAnswerAndQuestion_aacfde6a6691a807, []int{3}
}
func (m *DeleteQuestionReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteQuestionReply.Unmarshal(m, b)
}
func (m *DeleteQuestionReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteQuestionReply.Marshal(b, m, deterministic)
}
func (dst *DeleteQuestionReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteQuestionReply.Merge(dst, src)
}
func (m *DeleteQuestionReply) XXX_Size() int {
	return xxx_messageInfo_DeleteQuestionReply.Size(m)
}
func (m *DeleteQuestionReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteQuestionReply.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteQuestionReply proto.InternalMessageInfo

func (m *DeleteQuestionReply) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*DeleteAnswerRequest)(nil), "DeleteAnswerAndQuestion.DeleteAnswerRequest")
	proto.RegisterType((*DeleteAnswerReply)(nil), "DeleteAnswerAndQuestion.DeleteAnswerReply")
	proto.RegisterType((*DeleteQuestionRequest)(nil), "DeleteAnswerAndQuestion.DeleteQuestionRequest")
	proto.RegisterType((*DeleteQuestionReply)(nil), "DeleteAnswerAndQuestion.DeleteQuestionReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreeterClient interface {
	DeleteAnswer(ctx context.Context, in *DeleteAnswerRequest, opts ...grpc.CallOption) (*DeleteAnswerReply, error)
	DeleteQuestion(ctx context.Context, in *DeleteQuestionRequest, opts ...grpc.CallOption) (*DeleteQuestionReply, error)
}

type greeterClient struct {
	cc *grpc.ClientConn
}

func NewGreeterClient(cc *grpc.ClientConn) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) DeleteAnswer(ctx context.Context, in *DeleteAnswerRequest, opts ...grpc.CallOption) (*DeleteAnswerReply, error) {
	out := new(DeleteAnswerReply)
	err := c.cc.Invoke(ctx, "/DeleteAnswerAndQuestion.Greeter/DeleteAnswer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) DeleteQuestion(ctx context.Context, in *DeleteQuestionRequest, opts ...grpc.CallOption) (*DeleteQuestionReply, error) {
	out := new(DeleteQuestionReply)
	err := c.cc.Invoke(ctx, "/DeleteAnswerAndQuestion.Greeter/DeleteQuestion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreeterServer is the server API for Greeter service.
type GreeterServer interface {
	DeleteAnswer(context.Context, *DeleteAnswerRequest) (*DeleteAnswerReply, error)
	DeleteQuestion(context.Context, *DeleteQuestionRequest) (*DeleteQuestionReply, error)
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_DeleteAnswer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAnswerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).DeleteAnswer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DeleteAnswerAndQuestion.Greeter/DeleteAnswer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).DeleteAnswer(ctx, req.(*DeleteAnswerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_DeleteQuestion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteQuestionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).DeleteQuestion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DeleteAnswerAndQuestion.Greeter/DeleteQuestion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).DeleteQuestion(ctx, req.(*DeleteQuestionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "DeleteAnswerAndQuestion.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeleteAnswer",
			Handler:    _Greeter_DeleteAnswer_Handler,
		},
		{
			MethodName: "DeleteQuestion",
			Handler:    _Greeter_DeleteQuestion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "DeleteAnswerAndQuestion.proto",
}

func init() {
	proto.RegisterFile("DeleteAnswerAndQuestion.proto", fileDescriptor_DeleteAnswerAndQuestion_aacfde6a6691a807)
}

var fileDescriptor_DeleteAnswerAndQuestion_aacfde6a6691a807 = []byte{
	// 229 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x75, 0x49, 0xcd, 0x49,
	0x2d, 0x49, 0x75, 0xcc, 0x2b, 0x2e, 0x4f, 0x2d, 0x72, 0xcc, 0x4b, 0x09, 0x2c, 0x4d, 0x2d, 0x2e,
	0xc9, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0xc7, 0x21, 0xad, 0xe4, 0xcb,
	0x25, 0x8c, 0x2c, 0x15, 0x94, 0x5a, 0x08, 0x92, 0x11, 0x92, 0xe2, 0xe2, 0x80, 0x29, 0x91, 0x60,
	0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0xf3, 0x41, 0x72, 0x10, 0xc5, 0xa9, 0x45, 0x12, 0x4c, 0x10,
	0x39, 0x18, 0x5f, 0x49, 0x9b, 0x4b, 0x10, 0xd5, 0xb8, 0x82, 0x9c, 0x4a, 0x21, 0x31, 0x2e, 0xb6,
	0xa0, 0xd4, 0xe2, 0xd2, 0x9c, 0x12, 0xa8, 0x51, 0x50, 0x9e, 0x52, 0x30, 0x97, 0x28, 0x44, 0x31,
	0xcc, 0x68, 0x62, 0x6c, 0x97, 0xe3, 0xe2, 0x82, 0xb1, 0xe1, 0xf6, 0x23, 0x89, 0x28, 0xe9, 0xc2,
	0x3c, 0x84, 0x30, 0x14, 0x8f, 0x1b, 0x8c, 0x9e, 0x33, 0x72, 0xb1, 0xbb, 0x17, 0xa5, 0xa6, 0x96,
	0xa4, 0x16, 0x09, 0x65, 0x71, 0xf1, 0x20, 0x3b, 0x5e, 0x48, 0x47, 0x0f, 0x57, 0xa0, 0x62, 0x09,
	0x32, 0x29, 0x2d, 0x22, 0x55, 0x17, 0xe4, 0x54, 0x2a, 0x31, 0x08, 0x15, 0x70, 0xf1, 0xa1, 0x3a,
	0x53, 0x48, 0x8f, 0x80, 0x7e, 0xb4, 0x40, 0x92, 0xd2, 0x21, 0x5a, 0x3d, 0xd8, 0x46, 0x27, 0x21,
	0x2e, 0x81, 0xcc, 0x7c, 0xbd, 0xf4, 0xa2, 0x82, 0x64, 0xbd, 0xd4, 0x8a, 0xc4, 0xdc, 0x82, 0x9c,
	0xd4, 0xe2, 0x24, 0x36, 0x70, 0xea, 0x30, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xc9, 0x0a, 0x61,
	0x12, 0x3e, 0x02, 0x00, 0x00,
}
